services:
  server:
    image: ohttp-server
    ports:
      - "9443:9443"
    network_mode: "host"
    environment:
      - TARGET=http://localhost:3000
      - INSTANCE_SPECIFIC_KEY=1
    depends_on:
      - whisper

  whisper:
    image: whisper-api
    network_mode: "host"
    ports:
      - "5000:5000"